spring:
  application:
    name: technologyservice

  r2dbc:
    url: r2dbc:mysql://localhost:3306/tecnologia
    username: root
    password: 12345
    initialization:
      enabled: false   # desactiva schema.sql de Boot (usaremos Flyway)

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/tecnologia   # JDBC solo para migraciones
    user: root
    password: 12345
    locations: classpath:db/migration


  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.data.r2dbc: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  cache:
    disabled: true

appDescripcion: API para visualizar la traza de los pedidos
appVersion: 1.0.0
