spring:
  application:
    name: technologyservice

  r2dbc:
    url: r2dbc:mysql://localhost:3306/onclass
    username: root
    password: 12345

  sql:
    init:
      mode: always # para ejecutar schema.sql si lo usas
      platform: mysql

  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.data.r2dbc: DEBUG
