spring:
  application:
    name: technologyservice

  r2dbc:
    url: r2dbc:mysql://localhost:3306/onclass
    username: root
    password: 12345

  sql:
    init:
      mode: always
      platform: mysql

  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.data.r2dbc: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

  appDescripcion: API para visualizar la traza de los pedidos
  appVersion: 1.0.0
